sudo: required
services:
  - docker

env:
  global:
    - GIT_COMMIT=${TRAVIS_COMMIT::7}
    - GIT_BRANCH=$TRAVIS_BRANCH
    - CLIENT_REPO=$DOCKER_USERNAME/fibonacci-calculator-client
    - SERVER_REPO=$DOCKER_USERNAME/fibonacci-calculator-server
    - WORKER_REPO=$DOCKER_USERNAME/fibonacci-calculator-worker
    - NGINX_REPO=$DOCKER_USERNAME/fibonacci-calculator-nginx
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - openssl aes-256-cbc -K $encrypted_480ce5866b70_key -iv $encrypted_480ce5866b70_iv
    -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file=service-account.json
  - gcloud config set project universal-team-241804
  - gcloud config set compute/zone asia-southeast1-a
  - gcloud container clusters get-credentials fibonacci-calculator-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t $CLIENT_REPO-test -f ./client/Dockerfile.dev ./client

script:
  - docker run $CLIENT_REPO-test npm run test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
